apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
      - name: telemetry
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KAFKA_BROKER
          value: {{ .Values.env.KAFKA_BROKER }}
        - name: REDIS_URL
          value: {{ .Values.env.REDIS_URL }}